
name: quantum_kernel
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - setuptools
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn==0.24.1
  - scipy==1.6.1
  - tqdm==4.61.2
  - numexpr==2.7.1
  - ipykernel
  - statsmodels
  - pip:
    - qiskit==0.36.1
    - qiskit-machine-learning==0.4.0
    - qiskit-aer-gpu==0.8.2
    ##- mpi4py==3.1.3
